/// <autosync enabled="false">
/// <reference path="../lib/bootstrap-modal/2.2.4/bootstrap-modal.js" />
/// <reference path="../lib/bootstrap-modal/2.2.4/bootstrap-modalmanager.js" />
/// <reference path="../lib/datatables/1.10.0/jquery.dataTables.min.js" />
/// <reference path="../lib/html5.js" />
/// <reference path="../lib/icheck/jquery.icheck.min.js" />
/// <reference path="../lib/jquery/1.9.1/jquery.js" />
/// <reference path="../lib/layer/1.9.3/extend/layer.ext.js" />
/// <reference path="../lib/layer/1.9.3/layer.js" />
/// <reference path="../lib/laypage/1.2/laypage.js" />
/// <reference path="../lib/My97DatePicker/calendar.js" />
/// <reference path="../lib/My97DatePicker/WdatePicker.js" />
/// <reference path="H-ui.admin.js" />
/// <reference path="H-ui.js" />
